[project]
name = "fake-useragent"
version = "3.0.0"
license = "Apache-2.0"
description = "Up-to-date simple user-agent faker with real world database"
readme = "README.md"
keywords = [
  "agent",
  "fake",
  "fake user agent",
  "fake useragent",
  "user",
  "user agent",
  "useragent",
  "forge",
]
authors = [
  { name = "Melroy van den Berg", email = "melroy@melroy.org" },
  { name = "Victor Kovtun", email = "hellysmile@gmail.com" },
  { name = "hantang" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: OS Independent",
  "Operating System :: POSIX",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
]

[build-system]
requires = ["uv_build>=0.11.12,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
converter = [
  "requests>=2.32.4",
  "ua-parser>=1.0.0",
  "ua-parser-builtins>=0.18.0.post1",
  "ua-parser-rs>=0.1.2",
]
dev = [
  "mypy>=1.18.2",
  "pytest>=8.3.5",
  "pytest-cov>=6.0.0",
  "ruff>=0.11.13",
  "validate-pyproject>=0.24.1",
]

[tool.ruff]
target-version = "py310"
line-length = 142

lint.select = [
  "B",
  "C4",
  "C9",
  "D",   # Check compliance with Python docstring conventions.
  "E",
  "F",
  "I",
  "PL",
  "S",
  "SIM",
  "W",
  "YTT",
]
lint.ignore = [
  "B904",
  "C408",
  "D107",    # Allow no docstring in __init__, we document it in the class docstring.
  "PLW2901",
  "SIM105",
  "SIM108",
]
lint.per-file-ignores."docs/**/*" = [ "D" ]
lint.per-file-ignores."src/fake_useragent/__init__.py" = [ "F401" ]
lint.per-file-ignores."tests/**/*" = [ "D", "S", "SIM", "UP015" ]
lint.isort.known-first-party = [ "fake_useragent" ]
lint.mccabe.max-complexity = 13
lint.pydocstyle.convention = "google"
lint.pylint.max-args = 7
lint.pylint.max-branches = 13
