name: Update browsers.jsonl

on:
  schedule:
    - cron: "2 4 * * 0" # Sunday at 4:02
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-useragents:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      # USER: ${{ github.repository_owner }}
      # REPO: ${{ github.event.repository.name }}
      REMOTE_REPO: "intoli/user-agents"
      REPO_DIR: "temp"

    steps:
      - uses: actions/checkout@v6

      - name: Checkout data repo
        uses: actions/checkout@v6
        with:
          repository: ${{ env.REMOTE_REPO }}
          path: ${{ env.REPO_DIR }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Process source UA file and produce our JSONL
        run: uv run --group converter python scripts/convert-intoli-data.py --download

      - name: Validate generated user-agent dataset
        run: uv run python scripts/validate_dataset.py

      - name: Create Pull Request
        id: pr
        if: steps.git-check.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "[Bot] Update browsers.jsonl"
          title: Update browsers.jsonl file
          body: |
            This PR updates the browsers.jsonl file. 
            Data from [intoli/user-agents](https://github.com/intoli/user-agents).
          labels: ua-file
          branch: bot/data-update
          delete-branch: true

      # - name: Git auto commit
      #   uses: stefanzweifel/git-auto-commit-action@v7
      #   with:
      #     commit_user_name: "github-actions[bot]"
      #     commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
      #     commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
      #     commit_message: Automated update browsers.jsonl
      #     # commit_options: '--no-verify --signoff'
      #     # push_options: "--force"
      #     file_pattern: "*.jsonl"
