name: Update Bundled User Agents

on:
  schedule:
    - cron: '2 4 2 * 0'  # Run monthly (2nd day of the month) on Sunday at 4:02 at night
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-useragents:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true

    - name: Process source UA file and produce our JSONL
      run: uv run --group converter python ua-converter/ua_convert.py --download

    - name: Create Pull Request
      id: pr
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: Update bundled user agents
        branch: automated/ua-update
        title: Update bundled user agents file
        body: |
          This PR updates the bundled user agents file. 
          Thanks Intoli for the licence that permits us to use their data! 
          Check their work at [`user-agents`](https://github.com/intoli/user-agents).
        labels: ua-file
